[tools]
flux2 = "latest"
gh = "latest"
k3d = "latest"
k9s = "latest"
kubectl = "latest"
lsd = "latest"
pre-commit = "latest"
python = "3.13"
ruff = "latest"
trivy = "latest"
uv = "latest"   # Manage Python projects and dependencies

[settings]
python.uv_venv_auto = true   # UV will activate virtual environments automatically
experimental = true   # Works together with the previous setting
idiomatic_version_file_enable_tools = ["python"]   # Disable warnings when a Python version file is added

[env]   # Environment variables
APP_REPO = "devops-study-app"
GITOPS_REPO = "devops-study-app-gitops"
GITUSER = "maor-klir"

[hooks]
enter = "bash ./scripts/setup_project"   # The "enter" hook will be triggered when we SSH into our dev container

[tasks.k8s-setup-local]
description = "Set up a Kubernetes cluster that builds the local images and applies them"
run = "bash ./kubernetes/setup_cluster_local"

[tasks.k8s-setup-minimal]
description = "Set up a minimal Kubernetes cluster. Images are not applied onto the cluster."
run = "bash ./kubernetes/setup_cluster_minimal"

[tasks.e2e-tests]
description = "Run end-to-end tests on the Kubernetes deployment."
run = "cd ./kubernetes && uv run e2e-tests.py"

[tasks.setup-deploy-keys]
description = "Set up deploy keys for our repository."
run = "bash ./scripts/setup_deploy_keys"

[tasks.k8s-setup-gitops]
description = "Set up a Kubernets cluster configured with GitOps using Flux."
run = "bash ./kubernetes/setup_cluster_gitops"
